eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8765/eureka/
  instance:
    hostname: localhost

server:
  port: 8762
spring:
  application:
    name: client-hello

